version: 1
builder:
  configs:
    - platform: ios
      documentation_targets:
        - ThinPath
    - platform: macos-xcodebuild
      documentation_targets:
        - ThinPath
    - platform: watchos
      documentation_targets:
        - ThinPath
